spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 256859579187-knk2pll3e92nca1d19uh7dep4sf3q787.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
          naver:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: name,email,profile_image
            authorization-grant-type: authorization_code
            client-secret: kNUtXL6UiC
            client-id: sSRx9LWJipuCrEN7SdLk
            client-name: Naver
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token